/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false --env-interface=PosCloudflareEnv server/types/cloudflare-env.d.ts` (hash: 025eece4ac220c549b38cc11b85b016a)
interface __BaseEnv_PosCloudflareEnv {
	EMAIL: SendEmail;
	NUXT_MAIL_FROM: "info@microwest.ch";
	NUXT_MAIL_REPLY_TO: "info@microwest.ch";
	NUXT_PUBLIC_SITE_URL: string;
	TURSO_URL: string;
	TURSO_TOKEN: string;
	DB_REMOTE_TARGETS: string;
	POS_ALLOW_RUNTIME_SCHEMA_BOOTSTRAP: string;
	POS_ALLOW_RUNTIME_DEMO_SEED: string;
	MINIMAX_API_KEY: string;
	MINIMAX_MODEL: string;
	MINIMAX_BASE_URL: string;
	MAIL_FROM: string;
	MAIL_REPLY_TO: string;
	SHOPIFY_SHOP_DOMAIN: string;
	SHOPIFY_CLIENT_ID: string;
	SHOPIFY_CLIENT_SECRET: string;
	SHOPIFY_ADMIN_ACCESS_TOKEN: string;
	MOBILESENTRIX_BASE_URL: string;
	MOBILESENTRIX_CONSUMER_NAME: string;
	MOBILESENTRIX_CONSUMER_KEY: string;
	MOBILESENTRIX_CONSUMER_SECRET: string;
	MOBILESENTRIX_ACCESS_TOKEN: string;
	MOBILESENTRIX_ACCESS_TOKEN_SECRET: string;
	MOBILESENTRIX_REST_AUTH_HEADER_NAME: string;
	MOBILESENTRIX_REST_AUTH_HEADER_VALUE: string;
	NUXT_SESSION_PASSWORD: string;
	NUXT_PUBLIC_TURNSTILE_SITE_KEY: string;
	NUXT_TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_PosCloudflareEnv {}
}
interface PosCloudflareEnv extends __BaseEnv_PosCloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NUXT_MAIL_FROM" | "NUXT_MAIL_REPLY_TO" | "NUXT_PUBLIC_SITE_URL" | "TURSO_URL" | "TURSO_TOKEN" | "DB_REMOTE_TARGETS" | "POS_ALLOW_RUNTIME_SCHEMA_BOOTSTRAP" | "POS_ALLOW_RUNTIME_DEMO_SEED" | "MINIMAX_API_KEY" | "MINIMAX_MODEL" | "MINIMAX_BASE_URL" | "MAIL_FROM" | "MAIL_REPLY_TO" | "SHOPIFY_SHOP_DOMAIN" | "SHOPIFY_CLIENT_ID" | "SHOPIFY_CLIENT_SECRET" | "SHOPIFY_ADMIN_ACCESS_TOKEN" | "MOBILESENTRIX_BASE_URL" | "MOBILESENTRIX_CONSUMER_NAME" | "MOBILESENTRIX_CONSUMER_KEY" | "MOBILESENTRIX_CONSUMER_SECRET" | "MOBILESENTRIX_ACCESS_TOKEN" | "MOBILESENTRIX_ACCESS_TOKEN_SECRET" | "MOBILESENTRIX_REST_AUTH_HEADER_NAME" | "MOBILESENTRIX_REST_AUTH_HEADER_VALUE" | "NUXT_SESSION_PASSWORD" | "NUXT_PUBLIC_TURNSTILE_SITE_KEY" | "NUXT_TURNSTILE_SECRET_KEY">> {}
}
