import { describe, expect, it } from 'vitest'
import { createUnsavedReminder } from '../../shared/utils/unsaved-reminder'

describe('unsaved reminder clock', () => {
  it('waits five minutes after the latest input, then repeats every ten seconds without catching up missed beeps', () => {
    const reminder = createUnsavedReminder()
    reminder.change(true, 0)
    expect(reminder.tick(299_999)).toBe(false)
    reminder.change(true, 290_000)
    expect(reminder.tick(300_000)).toBe(false)
    expect(reminder.tick(590_000)).toBe(true)
    expect(reminder.tick(590_001)).toBe(false)
    expect(reminder.tick(599_999)).toBe(false)
    expect(reminder.tick(600_000)).toBe(true)
    expect(reminder.tick(609_999)).toBe(false)
    expect(reminder.tick(610_000)).toBe(true)
    expect(reminder.tick(2_000_000)).toBe(true)
    expect(reminder.tick(2_000_001)).toBe(false)
    expect(reminder.tick(2_009_999)).toBe(false)
    expect(reminder.tick(2_010_000)).toBe(true)
  })
  it('restarts the five-minute delay when editing resumes after a reminder', () => {
    const reminder = createUnsavedReminder()
    reminder.change(true, 0)
    expect(reminder.tick(300_000)).toBe(true)
    reminder.change(true, 305_000)
    expect(reminder.tick(310_000)).toBe(false)
    expect(reminder.tick(604_999)).toBe(false)
    expect(reminder.tick(605_000)).toBe(true)
    expect(reminder.tick(615_000)).toBe(true)
  })
  it('stops repeated reminders when changes are saved or discarded', () => {
    const reminder = createUnsavedReminder()
    reminder.change(true, 0)
    expect(reminder.tick(300_000)).toBe(true)
    reminder.change(false, 305_000)
    expect(reminder.tick(310_000)).toBe(false)
    expect(reminder.tick(900_000)).toBe(false)
  })
  it('silences until saving or discarding, including further input and failed saves', () => {
    const reminder = createUnsavedReminder()
    reminder.change(true, 0)
    expect(reminder.tick(300_000)).toBe(true)
    reminder.mute()
    expect(reminder.tick(310_000)).toBe(false)
    reminder.change(true, 320_000)
    expect(reminder.tick(620_000)).toBe(false)
    reminder.change(false, 630_000)
    expect(reminder.tick(900_000)).toBe(false)
    reminder.change(true, 1_000_000)
    expect(reminder.tick(1_300_000)).toBe(true)
  })
})
